// Partly generated by AI
//
// Ядро нашего линтера, где прописываем логику обхода AST-дерева
// и вызываем проверки правил. Тут же мы создаём объект Analyzer
package analyzer

import (
	"flag"
	"go/ast"
	"go/token"
	"regexp"
	"strings"
	"unicode"

	"github.com/PhosFactum/loglinter/internal/config"
	"golang.org/x/tools/go/analysis"
	"golang.org/x/tools/go/analysis/passes/inspect"
	"golang.org/x/tools/go/ast/inspector"
)

const Doc = `log-linter будет проверять всякие логи на соответствие правилам`

// Объект самого анализатора
var Analyzer = &analysis.Analyzer{
	Name:     "loglinter",
	Doc:      Doc,
	Run:      run,
	Requires: []*analysis.Analyzer{inspect.Analyzer},
}

// Флаги анализатора
var (
	configFlag = flag.String("config", "", "путь к конфигурационному файлу (JSON)")
)

// Здесь компилируется регулярное выражение для поиска чувствительныех данных
var sensitiveRegexp *regexp.Regexp
var forbiddenRunes []rune
var rulesConfig *config.Config

// AI-generated function
// run запускает основную функцию анализа
func run(pass *analysis.Pass) (interface{}, error) {
	// Загрузка конфигурации при первом запуске
	if sensitiveRegexp == nil {
		cfg, err := config.Load(*configFlag)
		if err != nil {
			pass.Reportf(pass.Files[0].Pos(), "failed to load config: %v", err)
			return nil, err
		}
		sensitiveRegexp, _ = cfg.BuildSensitiveRegex()
		forbiddenRunes = cfg.GetForbiddenRunes()
		rulesConfig = cfg
	}

	inspect := pass.ResultOf[inspect.Analyzer].(*inspector.Inspector)
	nodeFilter := []ast.Node{(*ast.CallExpr)(nil)}

	inspect.Preorder(nodeFilter, func(n ast.Node) {
		call := n.(*ast.CallExpr)
		if !isLoggerCall(call) {
			return
		}
		for _, msg := range extractMessages(call) {
			checkRules(pass, msg)
		}
	})
	return nil, nil
}

// isLoggerCall просто проверяет, является ли вызов функции логгером
func isLoggerCall(call *ast.CallExpr) bool {
	sel, ok := call.Fun.(*ast.SelectorExpr)
	if !ok {
		return false
	}
	pkg, ok := sel.X.(*ast.Ident)
	if !ok {
		return false
	}
	pkgs := map[string]bool{"log": true, "slog": true, "zap": true}
	methods := map[string]bool{
		"Debug": true, "Info": true, "Warn": true, "Error": true,
		"Print": true, "Println": true, "Printf": true,
		"Fatal": true, "Fatalln": true, "Fatalf": true,
		"Panic": true, "Panicln": true, "Panicf": true,
	}
	return pkgs[pkg.Name] && methods[sel.Sel.Name]
}

// extractMessages извлекает строковые аргументы вызова
func extractMessages(call *ast.CallExpr) []struct {
	text string
	pos  token.Pos
} {
	var res []struct {
		text string
		pos  token.Pos
	}
	for _, arg := range call.Args {
		if lit, ok := arg.(*ast.BasicLit); ok && lit.Kind == token.STRING {
			res = append(res, struct {
				text string
				pos  token.Pos
			}{text: strings.Trim(lit.Value, "\""), pos: lit.Pos()})
		}
	}
	return res
}

// checkRules проверяет соответствие 4-м исходным правилам
func checkRules(pass *analysis.Pass, msg struct {
	text string
	pos  token.Pos
}) {
	// Правило 1: строчная буква
	if rulesConfig.Rules.Lowercase.Enabled {
		if msg.text != "" && !unicode.IsLower([]rune(msg.text)[0]) {
			pass.Reportf(msg.pos, "лог должен начинаться с маленькой буквы: %q", msg.text)
		}
	}

	// Правило 2: только английский (ASCII)
	if rulesConfig.Rules.Language.Enabled {
		for _, r := range msg.text {
			// Не английские символы по ASCII начинались после 127-го кода
			if r > 127 {
				pass.Reportf(msg.pos, "лог должен быть на английском: %q", msg.text)
				break
			}
		}
	}

	// Правило 3: без спецсимволов и эмодзи
	if rulesConfig.Rules.Symbols.Enabled {
		for _, r := range msg.text {
			if isForbiddenRune(r) || isEmoji(r) {
				pass.Reportf(msg.pos, "лог не должен содержать спецсимволы: %q", msg.text)
				break
			}
		}
	}

	// Правило 4: без чувствительных данных
	if rulesConfig.Rules.Sensitive.Enabled {
		if sensitiveRegexp.MatchString(msg.text) {
			pass.Reportf(msg.pos, "лог содержит чувствительные данные: %q", msg.text)
		}
	}
}

// AI-generated function
// isEmoji просто сверяет, является ли эмодзи символ в логе
func isEmoji(r rune) bool {
	return (r >= 0x1F600 && r <= 0x1F64F) || (r >= 0x1F300 && r <= 0x1F5FF) ||
		(r >= 0x1F680 && r <= 0x1F6FF) || (r >= 0x1F1E0 && r <= 0x1F1FF) ||
		(r >= 0x2600 && r <= 0x26FF) || (r >= 0x2700 && r <= 0x27BF)
}

// isForbiddenRune проверяет, является ли руна запрещённым символом из конфига
func isForbiddenRune(r rune) bool {
	for _, f := range forbiddenRunes {
		if r == f {
			return true
		}
	}
	return false
}
