// Fully generated by AI
package main

import "log"

func main() {
	log.Println("Starting")            // want "лог должен начинаться с маленькой буквы"
	log.Println("запуск сервера")      // want "лог должен быть на английском"
	log.Println("server started!")     // want "лог не должен содержать спецсимволы"
	log.Println("password: secret123") // want "лог содержит чувствительные данные"
}
