// Partly generated by AI
// Вспомогательные функции для проверок условий
package utils

import (
	"unicode"
)

// IsLowercase проверяет, начинается ли строка с маленькой буквы
func IsLowercase(s string) bool {
	if len(s) == 0 {
		return true
	}
	firstRune := []rune(s)[0]
	// Если не буква — пропускаем проверку
	if !unicode.IsLetter(firstRune) {
		return true
	}
	return unicode.IsLower(firstRune)
}

// IsEnglishOnly проверяет, содержит ли строка только английские символы
func IsEnglishOnly(s string) bool {
	for _, r := range s {
		if r > 127 {
			return false
		}
	}
	return true
}

// AI-generated function
// IsEmoji проверяет, является ли руна эмодзи
func IsEmoji(r rune) bool {
	return (r >= 0x1F600 && r <= 0x1F64F) || // Emoticons
		(r >= 0x1F300 && r <= 0x1F5FF) || // Misc Symbols and Pictographs
		(r >= 0x1F680 && r <= 0x1F6FF) || // Transport and Map
		(r >= 0x1F1E0 && r <= 0x1F1FF) || // Flags
		(r >= 0x2600 && r <= 0x26FF) || // Misc symbols
		(r >= 0x2700 && r <= 0x27BF) || // Dingbats
		(r == 0x2B50 || r == 0x2B55) // Stars
}

// Набор запрещённых символов
var forbiddenSymbols = map[rune]struct{}{
	'!': {},
	'?': {},
	'…': {},
}

// HasForbiddenSymbols проверяет наличие запрещённых символов
func HasForbiddenSymbols(s string) bool {
	for _, r := range s {
		if _, ok := forbiddenSymbols[r]; ok {
			return true
		}
		if IsEmoji(r) {
			return true
		}
	}
	return false
}
